Moving proto files to repo root
Azure/azure-functions-dotnet-worker pull request #1221
Opened 2022-12-08 15:31 UTC by kshyju

Moving proto files to the repo root so that both DotNetWorker.Grpc project and FunctionsNetHost can use this single source of truth. Currently we have 2 copies.

1 . https://github.com/Azure/azure-functions-dotnet-worker/tree/main/src/DotNetWorker.Grpc/protobuf/src/proto
2. https://github.com/Azure/azure-functions-dotnet-worker/tree/main/host/src/Protos

2022-12-08 16:35 UTC, brettsam approved these changes

2022-12-08 16:41 UTC, satvu commented on host/src/Protos/CMakeLists.txt
> +# We cannot directly refer the proto files in the repo root as that dir is not a CMAKE Source dir.
great clarifying comments in this file

2022-12-08 16:41 UTC, satvu approved these changes

2022-12-08 18:21 UTC, liliankasem requested changes
We have a process around how we import the protobuf updates. The protobuf in the Grpc project is a clone of the protobuf repo. If we're moving it to protos folder at the root, we need to make sure we're following the same pattern

2022-12-09 16:31 UTC, kshyju commented
> We have a process around how we import the protobuf updates from the proto repo into the host and workers. The protobuf files in the Grpc folder are an exact copy of the protobuf repo. If we're moving it to protos folder at the root, we need to make sure we're following the same pattern and folder structure
> 
> Here's the protobuf repo: https://github.com/Azure/azure-functions-language-worker-protobuf
> 
> Protobuf release process: https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/EngineeringProcesses/ReleaseProcesses/ProtobufReleaseProcess.md&version=GBmaster&line=1

Kept the same folder structure as the protobuf repo.

2022-12-09 17:59 UTC, liliankasem approved these changes

2022-12-09 18:05 UTC, kshyju commented
/check-enforcer evaluate

2022-12-09 18:13 UTC, merged